### PR TITLE
Feature/load glits

### PR DESCRIPTION
**Pull request by royejac**

### CODE REVIEW

**Comment by royejac** [comment]
I believe the major conflicts coming from the "debugger" line.
I'll fix the conflict when the PR is approved.

Thanks in advance,
Roye.

**Comment by mhornstein** [comment]
As we spoke about the changes required due to the addition of the host Service and the TCP suppot + other changes you mentioned you intend to add I guess there are more updates coming :)

In the meantime, I'm attaching some thoughs.

Kudos for the great first commit after  handling loads of code :) !

**Comment by royejac** [comment]
Hey Maor, how are you? :)
Please make CR when you are availabe. 

Thanks in advance,
Roye.

**Comment by royejac** [comment]
Fixes of the rellevant issues of the CR has been done and published to the branch.
PR is completed, feature/loadGlits is merged to master.

**Pull request merged**
